const ERROR_NOT_FOUND = 404;
const ERROR_SERVER = 500;
const ERROR_INCORRECT_DATA = 400;
const STATUS_OK = 200;
const STATUS_CREATED = 201;
const ERROR_UNAUTHORIZED = 401;
const ERROR_CONFLICT = 409;
const ERROR_FORBIDDEN = 403;

module.exports = {
  ERROR_NOT_FOUND,
  ERROR_SERVER,
  ERROR_INCORRECT_DATA,
  STATUS_OK,
  STATUS_CREATED,
  ERROR_UNAUTHORIZED,
  ERROR_CONFLICT,
  ERROR_FORBIDDEN,
};
